### ISSUE TITLE
How to change image

### ISSUE THREAD

**Issue by winstondarkblueee** [Bartuzen/NotepadRPC#10]
I want change small and large image but i dont know how to.
![image](https://user-images.githubusercontent.com/71168855/119997656-9fd04600-bfd8-11eb-88e1-602cbba6a4ac.png)
I try add url but not working.

**Comment by Bartuzen** [comment]
I explained how to change RPC image in issue #9. Please refer to that issue and feel free to ask if you need more help.

**Comment by winstondarkblueee** [comment]
Thx, i got it and did it.

![image](https://user-images.githubusercontent.com/71168855/120064393-8d0b4f00-c074-11eb-9570-deb2e6b2945f.png)
now looks better.
