### ISSUE TITLE
Ubuntu Not Working

### ISSUE THREAD

**Issue by nemmie99** [Bartuzen/NotepadRPC#2]
I do not know the Python language, and this may be an error on my part, but after attempting to run NotepadRPC.py on Ubuntu, it does not seem to work... This is the error I am getting.

Couldn't find required libraries. Trying to install them...
/usr/bin/python3: No module named pip
Couldn't install pypresence

**Comment by lloydtao** [comment]
Your machine needs `pypresence` from pip (as well as `ruamel.base`). I've opened an issue #3, and a fix #4, that you can check-out and run/test. Drop a comment on the pull request with your results 😛

**Comment by democat3457** [comment]
can probably also be closed

**Comment by nemmie99** [comment]
Yes. Thank you @LloydTao .
