### ISSUE TITLE
Ability to change the RP Image

### ISSUE THREAD

**Issue by modkavartini** [Bartuzen/NotepadRPC#9]
I would like an option to change the Image used for the Rich Prescence, if there is already a way to do this, could someone tell me how?

**Comment by Bartuzen** [comment]
To change the image, you need to create a new application on Discord and add image to that applicaton. To do this, you can follow these steps:
1. Go to [Discord Developer Portal](https://discord.com/developers/applications).
2. Click on `New Application` and create a new application.
3. Replace `clientId` in config with `Application ID` from the application you just created.
4. Go to rich presence section in the application.
5. Click on `Add Image(s)` and add your preferred image, then rename the image to `image_large`.
